traj_prediction/fit_len: 10
traj_prediction/check_len: 10
traj_prediction/fitKd_len: 15

traj_prediction/freeFallCheck_err: 0.5

traj_prediction/pre_time: 2.0
traj_prediction/pre_size: 16

traj_prediction/beta: 0.3